apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-deployment
  template:
    metadata:
      labels:
        app: java-deployment
    spec:
      containers:
        - name: java-spring-boot  
          image: java-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-deployment
spec:
  selector:
    app: java-deployment
  ports:
    - protocol: TCP 
      port: 9292        # This is the port exposed by the service
      targetPort: 8080  # This is the port on the container
  type: NodePort
