name: Java App Deployment

# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t java-app:latest .

      - name: Start Minikube
        run: |
          minikube start

      # - name: Set Kubeconfig for Minikube
      #   run: |
      #     export KUBEVERSION=$(minikube kubectl -- get --raw /version)
      #     alias kubectl="minikube kubectl --"
      #     kubectl version

      - name: Deploy to Kubernetes (Minikube)
        run: |
          kubectl apply -f deployment.yml
          minikube service java-deployment --url
