name: Build and Push to AWS Public ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Verify Docker Login
        run: docker info

      - name: Tag Docker image
        run: |
          docker tag my-app-image:latest ${{ secrets.PUBLIC_ECR_REPO_URL }}/my-app-image:latest

      - name: Push Docker image to Amazon Public ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
