name: SSH to Local Machine

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # ssh-keyscan -H 192.168.1.38 >> ~/.ssh/known_hosts

      - name: SSH into local machine and run command
        run: |
          ssh -i ~/.ssh/id_rsa pulse30@192.168.1.37 "echo Hi"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}








# name: Java App Deployment

# on:
#   workflow_dispatch: 
#     branches:
#       - main

#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Uncomment the lines below to enable Docker Hub login (if needed)
#       # - name: Login to Docker Hub
#       #   env:
#       #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#       #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#       #   run: |
#       #     echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

#       - name: Build Docker image
#         run: |
#           docker build -t java-app:latest .

#       # - name: Start Minikube
#       #   run: |
#       #     minikube start

#       - name: Set Kubeconfig for Minikube
#         run: |
#           minikube start
#           export KUBEVERSION=$(minikube kubectl -- get --raw /version)
#           alias kubectl="minikube kubectl --"
#           kubectl version

#       - name: Deploy to Kubernetes (Minikube)
#         run: |
#           kubectl apply -f deployment.yml
#           minikube service java-deployment --url


