name: Build and Push to AWS Public ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app-image:latest .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin public.ecr.aws

      - name: Verify Docker Login
        run: docker info

      - name: Tag Docker image
        run: |
          docker tag my-app-image:latest ${{ secrets.PUBLIC_ECR_REPO_URL }}/my-app-image:latest

      - name: Push Docker image to Amazon Public ECR
        run: |
          docker push ${{ secrets.PUBLIC_ECR_REPO_URL }}/my-app-image:latest
